services:
  # Backend service
  - type: web
    name: chat-app
    env: node
    region: oregon
    plan: free
    buildCommand: |
      # Debug: Show current directory and environment
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      
      # Clean install dependencies
      echo "Installing dependencies..."
      yarn install --frozen-lockfile
      
      # Build frontend with explicit steps
      echo "Building frontend..."
      cd client
      echo "Client directory contents:"
      ls -la
      echo "Running vite build..."
      yarn build
      echo "Checking dist directory:"
      ls -la dist || echo "dist directory not found!"
      echo "Checking dist contents:"
      ls -la dist/ || echo "dist directory is empty!"
      cd ..
      
      # Final directory check
      echo "Final directory structure:"
      ls -la
      echo "Checking client/dist:"
      ls -la client/dist || echo "client/dist not found!"
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: "10000"
      - key: VITE_API_URL
        value: "https://chat-app.onrender.com"

  # Frontend service
  - type: web
    name: chat-app-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html