services:
  # Backend service
  - type: web
    name: chat-app
    env: node
    region: oregon
    plan: free
    buildCommand: |
      # Make build script executable and run it
      chmod +x build.sh
      ./build.sh
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: "10000"
      - key: VITE_API_URL
        value: "https://chat-app.onrender.com"

  # Frontend service
  - type: web
    name: chat-app-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html