services:
  # Backend service
  - type: web
    name: chat-app
    env: node
    region: oregon
    plan: free
    buildCommand: |
      # Install root dependencies
      npm install
      # Install and build frontend
      cd client && npm install && npm run build
      # Install backend dependencies
      cd ../server && npm install
      # Return to root
      cd ..
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false

  # Frontend service
  - type: web
    name: chat-app-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html