services:
  # Backend service
  - type: web
    name: chat-app-backend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd server && yarn install
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: "https://chat-app-frontend.vercel.app"
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "https://chat-app-frontend.vercel.app"

  # Frontend service
  - type: web
    name: chat-app-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html