services:
  # Backend service
  - type: web
    name: chat-app
    env: node
    region: oregon
    plan: free
    buildCommand: |
      # Debug: Show current directory
      pwd
      ls -la
      
      # Install dependencies using workspaces
      yarn install
      
      # Build frontend
      echo "Building frontend..."
      cd client
      yarn build
      ls -la dist
      cd ..
      
      # Debug: Show final structure
      echo "Final directory structure:"
      ls -la
      ls -la client/dist
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: "10000"

  # Frontend service
  - type: web
    name: chat-app-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html